name: Collect download count of GitHub repos

on:
  #schedule:
    # Runs every day
    #- cron: ''
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  collect-download-count:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4

      - name: Run PowerShell script to collect download count
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          .github/scripts/collectdownloadcount.ps1 -TargetRepoFilePath '.github/scripts/target-repos.json' -OutputFolderPath 'statistics/downloads'

      - name: Commit and Push collected data
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ -n "$(git status --porcelain statistics/downloads)" ]; then
  
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"

            git add statistics/downloads
            git commit -m "Update download count data."
            git push
          else
            echo "No changes to commit."
          fi
