name: Collect star count

on:
  schedule:
    - cron: '0 1 * * *'  # Runs every day at 01:00 UTC
  workflow_dispatch:     # Allows you to run this workflow manually from the Actions tab

permissions:
  contents: write

env:
  TARGET_REPO_FILE_PATH: .github/scripts/collectstarcount-target-repos.json
  OUTPUT_DIR_PATH: statistics/stars

jobs:
  collect-download-count:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4

      - name: Run PowerShell script to collect star count
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          .github/scripts/collectstarcount.ps1 -TargetRepoFilePath $env:TARGET_REPO_FILE_PATH -OutputFolderPath $env:OUTPUT_DIR_PATH

      - name: Commit and Push collected data
        env:
          COMMIT_MESSAGE: Update star count data
        run: |
          if [ -n "$(git status --porcelain $OUTPUT_DIR_PATH)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add $OUTPUT_DIR_PATH
            git commit -m "$COMMIT_MESSAGE"
            git push
          else
            echo "No changes to commit."
          fi
