name: Collect download count of GitHub repos

on:
  #schedule:
    # Runs every day
    #- cron: ''
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write

env:
  TARGET_REPO_FILE_PATH: .github/scripts/target-repos.json
  OUTPUT_DIR_PATH: statistics/downloads

jobs:
  collect-download-count:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4

      - name: Run PowerShell script to collect download count
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          .github/scripts/collectdownloadcount.ps1 -TargetRepoFilePath $env:TARGET_REPO_FILE_PATH -OutputFolderPath $env:OUTPUT_DIR_PATH

      - name: Commit and Push collected data
        run: |
          if [ -n "$(git status --porcelain $OUTPUT_DIR_PATH)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add $OUTPUT_DIR_PATH
            git commit -m "Update download count data."
            git push
          else
            echo "No changes to commit."
          fi
