name: Update stats summary

on:
  schedule:
    - cron: '0 1 * * *'  # Runs every day at 01:00 UTC
  workflow_dispatch:     # Allows you to run this workflow manually from the Actions tab

permissions:
  contents: write

env:
  OUTPUT_FILE_PATH: statistics/README.md

jobs:
  update-profile-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v6

      - name: Run PowerShell script to update stats summary
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ secrets.STATS_SUMMARY_TOKEN }}
          SCRIPT_FILE_PATH: .github/scripts/update-summary.ps1
          TEMPLATE_FILE_PATH: .github/scripts/summary-template.md
        run: |
          & $env:SCRIPT_FILE_PATH -TemplateFilePath $env:TEMPLATE_FILE_PATH -OutputFilePath $env:OUTPUT_FILE_PATH

      - name: Commit and Push updated stats summary
        env:
          COMMIT_USER_NAME: github-actions[bot]
          COMMIT_USER_EMAIL: github-actions[bot]@users.noreply.github.com
          COMMIT_MESSAGE: Update stats summary
        run: |
          if [ -n "$(git status --porcelain $OUTPUT_FILE_PATH)" ]; then
            git config user.name "$COMMIT_USER_NAME"
            git config user.email "$COMMIT_USER_EMAIL"
            git add $OUTPUT_FILE_PATH
            git commit -m "$COMMIT_MESSAGE"
            git push
          else
            echo "No changes to commit."
          fi
